version: "3.7"
services:
  redis:
    image: redis:5
    ports:
      - "6379"
  virtuoso:
    image: tenforce/virtuoso:virtuoso7.2.5
    environment:
      DBA_PASSWORD: dba
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: http://www.example.com/my-graph
    ports:
      - "8890"
      - "1111"
  api:
    build: .
    ports:
      - "${HARVESTER_PUBLIC_PORT:-9090}:5000"
    depends_on:
      - redis
      - virtuoso
    environment:
      HARVESTER_LOG_LEVEL: ${HARVESTER_LOG_LEVEL:-debug}
      HARVESTER_VALIDATOR_DISABLED: ${HARVESTER_VALIDATOR_DISABLED:-}
      HARVESTER_SOURCES: ${HARVESTER_SOURCES}
  worker:
    build: .
    depends_on:
      - redis
      - virtuoso
    environment:
      HARVESTER_LOG_LEVEL: ${HARVESTER_LOG_LEVEL:-debug}
    command:
      [
        "/usr/local/bin/rq",
        "worker",
        "--with-scheduler",
        "--url",
        "redis://redis",
      ]
